server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: truong0962935943@gmail.com
    password: bueq rtjd ghst qvdn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "QU+SwOanBr5XdqvBrRMEu07JkXekyENmTcEpklJ2hSB3QjE/hicft/WwBl1JK+v/"