server:
  port: 8088

spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: mysql://root:gRsKHVsFNszbMuvGLKUZQaaSTzOiLCfG@mysql.railway.internal:3306/railway
    username: root
    password: gRsKHVsFNszbMuvGLKUZQaaSTzOiLCfG
    driverClassName: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  signerKey: "QU+SwOanBr5XdqvBrRMEu07JkXekyENmTcEpklJ2hSB3QjE/hicft/WwBl1JK+v/"